# Generated by Django 4.2.15 on 2025-11-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="virtualcard",
            old_name="expiration_date",
            new_name="expiry_date",
        ),
    ]
