# Generated by Django 4.2.15 on 2025-06-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_currency",
            field=models.CharField(
                blank=True,
                choices=[("usd", "USD"), ("eur", "EUR"), ("xaf", "XAF")],
                max_length=3,
                null=True,
                verbose_name="Account Currency",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("current", "Current"),
                    ("savings", "Savings"),
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                ],
                max_length=20,
                null=True,
                verbose_name="Account Type",
            ),
        ),
    ]
