# Generated by Django 4.2.15 on 2025-06-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_profile_account_currency_profile_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="account_currency",
            field=models.CharField(
                blank=True,
                choices=[("usd", "USD"), ("eur", "EUR"), ("xaf", "XAF")],
                default="xaf",
                max_length=3,
                null=True,
                verbose_name="Account Currency",
            ),
        ),
    ]
