services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    volumes:
      - .:/app:z
      - ./staticfiles:/app/staticfiles
#    ports:
#      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./.envs/.env.local
    depends_on:
      - postgres
      - mailpit
      - redis
      - rabbitmq
    command: /start.sh
    networks:
      - pybank_local_nw

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - pybank_local_db:/var.lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - pybank_local_nw
  mailpit:
    image: docker.io/axllent/mailpit:v1.20.3
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - pybank_mailpit_db:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - pybank_local_nw

  redis:
    image: redis:7.0-alpine3.19
    command: redis-server --appendonly yes
    networks:
      - pybank_local_nw

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - pybank_local_nw

  celeryworker:
    <<: *api
    command: /start-celeryworker.sh

  flower:
    <<: *api
    command: /start-flower.sh
    ports:
      - "5555:5555"
    volumes:
      - flower_db:/app/flower_db

  celerybeat:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    env_file:
      - ./.envs/.env.local
    depends_on:
      - postgres
      - redis
      - rabbitmq
    command: /start-celerybeat.sh
    networks:
      - pybank_local_nw

  nginx:
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./staticfiles:/app/staticfiles
      - logs_store:/var/log/nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - pybank_local_nw

networks:
  pybank_local_nw:
    external: true

volumes:
    pybank_local_db:
    pybank_mailpit_db:
    logs_store:
    rabbitmq_data:
    rabbitmq_log:
    flower_db:
