# Generated by Django 4.2.15 on 2025-06-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="account_number",
            field=models.CharField(
                default=1111111111111111,
                max_length=20,
                unique=True,
                verbose_name="Account Number",
            ),
            preserve_default=False,
        ),
    ]
