# Generated by Django 4.2.15 on 2025-11-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_bankaccount_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Annual interest rate as a decimal (e.g 0.020 for 2.0%)",
                max_digits=5,
                verbose_name="Interest Rate",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("interest", "Interest"),
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("transfer", "Transfer"),
                ],
                default="deposit",
                max_length=20,
            ),
        ),
    ]
