# Generated by Django 4.2.15 on 2025-05-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(
                blank=True, default=123456, max_length=8, verbose_name="OTP"
            ),
            preserve_default=False,
        ),
    ]
